services:
  app:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: floresta
    ports:
      - "3001:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -lc "npm install -yqq && npm run dev"
  
  api:
    image: mamura/php-dev:latest
    container_name: api-floresta
    healthcheck:
      disable: true
    labels:
      - "traefik.enable=true" 
    volumes:
      - ./api:/src
    environment:
      - PROJECT_WEBROOT=/src/public
    ports:
      # - "80:80"
      - "5173:5173" # Vite

  mysql:
    image: mysql:8.0
    container_name: floresta-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: floresta
      MYSQL_USER: floresta
      MYSQL_PASSWORD: floresta
    ports:
      - "3307:3306"
    volumes:
      - mysql_floresta:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: floresta-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  mongodb:
    image: mongo:7
    container_name: floresta-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: floresta
    ports:
      - "27017:27017"
    volumes:
      - mongodb_floresta:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: floresta-mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"

volumes:
  mysql_floresta:
  mongodb_floresta:
 
networks:
  default:
      name: dev-network
      external: true